# Seção 2: Introdução à Lib NumPy

___

# Imports para a Aula

In [1]:
import numpy as np

___

# Tutorial

## Tipos Numéricos Auxiliares

### Not A Number

#### Definição

In [2]:
np.nan

nan

In [3]:
-np.nan

nan

#### Propriedades

In [4]:
np.nan == 0

False

In [5]:
np.nan > 0

False

In [6]:
np.nan < 0

False

In [7]:
np.nan == np.nan

False

In [8]:
1. > np.nan

False

### Infinito

#### Definição

In [9]:
np.inf

inf

In [10]:
-np.inf

-inf

In [11]:
1. / 0.

ZeroDivisionError: float division by zero

In [12]:
np.float32(1.) / np.float32(0)

C:\Users\allan\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in float_scalars
  """Entry point for launching an IPython kernel.


inf

#### Propriedades

In [13]:
np.inf == np.inf

True

In [14]:
-np.inf == np.inf

False

In [15]:
np.inf/np.inf

nan

In [16]:
np.inf/(-np.inf)

nan

In [17]:
biggest_uint = np.iinfo(np.uint64).max
print(biggest_uint)
np.inf > biggest_uint

18446744073709551615


True

In [18]:
-np.inf < -biggest_uint

True

In [19]:
np.inf > -np.inf

True

## _Arrays_ e Matrizes

### 1D Array

In [20]:
""" inicializando com uma list """   
x = [1, 2, 3, 4, 5, 6, 7, 8, 9]
np.array(x)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
""" inicializando com uma tupla """   
x = (1, 2, 3, 4, 5, 6, 7, 8, 9)
np.array(x)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
""" inicializando diretamente """   
np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### Matriz = 2D Array

In [23]:
""" list de lists """   
x = [
    [1, 2, 3, 4, 5, 6, 7, 8, 9],
    [1, 2, 3, 4, 5, 6, 7, 8, 9],
    [1, 2, 3, 4, 5, 6, 7, 8, 9],
    [1, 2, 3, 4, 5, 6, 7, 8, 9],
    [1, 2, 3, 4, 5, 6, 7, 8, 9]
]
np.array(x)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [24]:
""" lista de arrays """   
x = [
    np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
    np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
    np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
    np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
    np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
]
np.array(x)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9]])

##  Acessando valores em um _array_

### Definição das Variáveis

In [25]:
x_1d = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
x_2d = np.array([
    x_1d, 
    x_1d + 1, 
    x_1d + 2, 
    x_1d + 3, 
    x_1d + 4
])
x_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13]])

### Slicing

#### 1D (índices)

In [27]:
x_1d[3]

3

In [28]:
x_1d[[3, 2]]

array([3, 2])

#### 1D (intervalos)

In [29]:
x_1d[2:7:2]

array([2, 4, 6])

In [30]:
x_1d[:8:3]

array([0, 3, 6])

In [31]:
x_1d[7:9]

array([7, 8])

In [32]:
x_1d[:4]

array([0, 1, 2, 3])

In [33]:
x_1d[::3]

array([0, 3, 6, 9])

In [34]:
x_1d[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [35]:
x_1d[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
a = x_1d.copy()

In [37]:
a[3] = 30


In [38]:
x_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
a

array([ 0,  1,  2, 30,  4,  5,  6,  7,  8,  9])

In [40]:
np.array([a[:2], a[3:5]])

array([[ 0,  1],
       [30,  4]])

#### 2D (índices)

In [41]:
x_2d[3]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [42]:
x_2d[3][5]

8

In [43]:
x_2d[3, 5]

8

In [44]:
x_2d[[3, 2]]

array([[ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [45]:
x_2d[[3, 2], 2]

array([5, 4])

#### 2D (intervalos)

In [46]:
x_2d[[2, 4], 4:6]

array([[6, 7],
       [8, 9]])

In [47]:
x_2d[2:4, [2, 4, 5]]

array([[4, 6, 7],
       [5, 7, 8]])

In [48]:
x_2d[2:4, :5]

array([[2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

### Masks

#### Conceito

In [49]:
""" mask = array(bool) """
index = x_2d[:, :6] >  4

In [50]:
index.dtype

dtype('bool')

In [51]:
index

array([[False, False, False, False, False,  True],
       [False, False, False, False,  True,  True],
       [False, False, False,  True,  True,  True],
       [False, False,  True,  True,  True,  True],
       [False,  True,  True,  True,  True,  True]], dtype=bool)

#### Aplicação

In [52]:
""" Nota sobre o método `copy`:  
    
    Caso não seja utilizado, modificar um valor no slice 
    é a mesma coisa que modificar na variável original.
    
"""
tmp = x_2d[:, :8].copy()
tmp

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 2,  3,  4,  5,  6,  7,  8,  9],
       [ 3,  4,  5,  6,  7,  8,  9, 10],
       [ 4,  5,  6,  7,  8,  9, 10, 11]])

In [53]:
tmp[tmp >  6] = 13
tmp[tmp <  2] = -13
tmp

array([[-13, -13,   2,   3,   4,   5,   6,  13],
       [-13,   2,   3,   4,   5,   6,  13,  13],
       [  2,   3,   4,   5,   6,  13,  13,  13],
       [  3,   4,   5,   6,  13,  13,  13,  13],
       [  4,   5,   6,  13,  13,  13,  13,  13]])

In [54]:
tmp[(tmp == -13) | (tmp == 13)] = 0
tmp

array([[0, 0, 2, 3, 4, 5, 6, 0],
       [0, 2, 3, 4, 5, 6, 0, 0],
       [2, 3, 4, 5, 6, 0, 0, 0],
       [3, 4, 5, 6, 0, 0, 0, 0],
       [4, 5, 6, 0, 0, 0, 0, 0]])

In [55]:
tmp[(tmp > 0) & (tmp < 6)] = -3
tmp

array([[ 0,  0, -3, -3, -3, -3,  6,  0],
       [ 0, -3, -3, -3, -3,  6,  0,  0],
       [-3, -3, -3, -3,  6,  0,  0,  0],
       [-3, -3, -3,  6,  0,  0,  0,  0],
       [-3, -3,  6,  0,  0,  0,  0,  0]])

## Operações Vetoriais

### Definição das Variáveis:

In [56]:
A = np.array([
    [1, 2, 0, -4],
    [0, 2, 3, -1],
    [1, 0, 3,  0],
])

In [57]:
B = np.array([
    [-1,  0,  2],
    [ 0, -1, -2],
])

In [58]:
C = np.array([
    [ 1,  0,  2],
    [ 1,  3,  0],
])

In [59]:
D = np.array([ 3,  5,  2])

### Concatenação

In [60]:
np.hstack((B, C))

array([[-1,  0,  2,  1,  0,  2],
       [ 0, -1, -2,  1,  3,  0]])

In [61]:
np.vstack((B, C))

array([[-1,  0,  2],
       [ 0, -1, -2],
       [ 1,  0,  2],
       [ 1,  3,  0]])

### Transposição:

In [62]:
A


array([[ 1,  2,  0, -4],
       [ 0,  2,  3, -1],
       [ 1,  0,  3,  0]])

In [63]:
np.transpose(A)

array([[ 1,  0,  1],
       [ 2,  2,  0],
       [ 0,  3,  3],
       [-4, -1,  0]])

In [64]:
B.T

array([[-1,  0],
       [ 0, -1],
       [ 2, -2]])

### Operações Escalares Simples:

In [65]:
A + 1

array([[ 2,  3,  1, -3],
       [ 1,  3,  4,  0],
       [ 2,  1,  4,  1]])

In [66]:
B * 10

array([[-10,   0,  20],
       [  0, -10, -20]])

In [67]:
C ** 3

array([[ 1,  0,  8],
       [ 1, 27,  0]], dtype=int32)

In [68]:
B.shape, C.shape

((2, 3), (2, 3))

In [69]:
B - C

array([[-2,  0,  0],
       [-1, -4, -2]])

In [70]:
B * C

array([[-1,  0,  4],
       [ 0, -3,  0]])

In [71]:
(B + 10) / ((C ** 2) + 10)

array([[ 0.81818182,  1.        ,  0.85714286],
       [ 0.90909091,  0.47368421,  0.8       ]])

### Operações Escalares Propagadas:

In [72]:
B

array([[-1,  0,  2],
       [ 0, -1, -2]])

In [73]:
D.reshape([3, 1])[:2]

array([[3],
       [5]])

In [74]:
B / D

array([[-0.33333333,  0.        ,  1.        ],
       [ 0.        , -0.2       , -1.        ]])

In [75]:
B / D.reshape([3, 1][:2]).T

array([[-0.33333333,  0.        ,  1.        ],
       [ 0.        , -0.2       , -1.        ]])

In [76]:
A.T * D

array([[  3,   0,   2],
       [  6,  10,   0],
       [  0,  15,   6],
       [-12,  -5,   0]])

In [77]:
C + D

array([[4, 5, 4],
       [4, 8, 2]])

### Operações Vetoriais:

In [78]:
B.shape

(2, 3)

In [79]:
D.reshape([3,1]).shape

(3, 1)

In [80]:
B.dot(D.reshape([3,1])).shape

(2, 1)

In [81]:
A.shape, B.shape

((3, 4), (2, 3))

In [82]:
""" Vai dar erro, pois as dimensões são incompatíveis """
A.dot(B)

ValueError: shapes (3,4) and (2,3) not aligned: 4 (dim 1) != 2 (dim 0)

In [83]:
np.dot(A.T, B.T)

array([[ 1, -2],
       [-2, -2],
       [ 6, -9],
       [ 4,  1]])

In [84]:
X = np.dot(A.T, B.T).dot(B.dot(D))
X

array([19, 16, 87, -5])

In [85]:
Y = np.array([X])
Y

array([[19, 16, 87, -5]])

In [86]:
Y.shape

(1, 4)

In [87]:
Y.T.dot(Y)

array([[ 361,  304, 1653,  -95],
       [ 304,  256, 1392,  -80],
       [1653, 1392, 7569, -435],
       [ -95,  -80, -435,   25]])

In [88]:
Y.dot(Y.T)

array([[8211]])

### Propagação de Operações:

##### * Numéricos

In [89]:
B

array([[-1,  0,  2],
       [ 0, -1, -2]])

In [90]:
B.sum()

-2

In [91]:
B.sum(axis=0)

array([-1, -1,  0])

In [92]:
B.sum(axis=1)

array([ 1, -3])

In [93]:
B.mean(axis=1)

array([ 0.33333333, -1.        ])

In [94]:
B.std(axis=1)

array([ 1.24721913,  0.81649658])

##### * Lógicos

In [95]:
(B > 0)

array([[False, False,  True],
       [False, False, False]], dtype=bool)

In [96]:
(B > 0).all(axis=1)

array([False, False], dtype=bool)

In [97]:
(B > 0).any(axis=1)

array([ True, False], dtype=bool)

## Geradores

### Repetidores

#### zeros

In [98]:
np.zeros((3,7))

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.]])

#### ones

In [99]:
np.ones((3,7))

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.]])

#### tile

In [100]:
A = np.array([[1, 2, 3, 4, 5]])
A

array([[1, 2, 3, 4, 5]])

In [101]:
np.tile(A, (3, 1))

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [102]:
np.tile(A.T, (1,4))

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4],
       [5, 5, 5, 5]])

In [103]:
np.tile(A.T, (2, 4))

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4],
       [5, 5, 5, 5],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4],
       [5, 5, 5, 5]])

#### eye (Matriz Identidade)

In [104]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

### Transformadores:

#### Variável Auxiliar

In [105]:
A = np.tile(np.array([[1, 2, 3, 4]]), (4, 1))
A

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

#### TRIL

In [106]:
np.tril(A)

array([[1, 0, 0, 0],
       [1, 2, 0, 0],
       [1, 2, 3, 0],
       [1, 2, 3, 4]])

In [107]:
np.tril(A, 1)

array([[1, 2, 0, 0],
       [1, 2, 3, 0],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [108]:
np.tril(A, -1)

array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 2, 0, 0],
       [1, 2, 3, 0]])

#### TRIU

In [109]:
np.triu(A)

array([[1, 2, 3, 4],
       [0, 2, 3, 4],
       [0, 0, 3, 4],
       [0, 0, 0, 4]])

In [110]:
np.triu(A, 1)

array([[0, 2, 3, 4],
       [0, 0, 3, 4],
       [0, 0, 0, 4],
       [0, 0, 0, 0]])

In [111]:
np.triu(A, -1)

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [0, 2, 3, 4],
       [0, 0, 3, 4]])

___

# Desafio

## Objetivo:

Construir a **saída esperada** usando as **ferramentas** dadas em cada item.

### [ Exemplo ]

#### Saída Esperada:

In [112]:
np.array([
    [ 1., 0., -1.],
    [ 0., 0.,  0.],
    [-1., 0.,  1.]
])

array([[ 1.,  0., -1.],
       [ 0.,  0.,  0.],
       [-1.,  0.,  1.]])

#### Ferramentas:

In [113]:
np.eye?

#### Solução:

In [114]:
np.eye(3) - np.eye(3)[::-1]

array([[ 1.,  0., -1.],
       [ 0.,  0.,  0.],
       [-1.,  0.,  1.]])

### [ Item A ]

#### Saída Esperada:

In [115]:
np.array([[-1.,  0.,  0., 0.],
          [-1., -1.,  0., 0.],
          [-1., -1., -1., 0.]])

array([[-1.,  0.,  0.,  0.],
       [-1., -1.,  0.,  0.],
       [-1., -1., -1.,  0.]])

#### Ferramentas:

In [116]:
np.ones?

In [117]:
np.tril?

#### Solução:

In [118]:
np.tril(-np.ones((3, 4)))

array([[-1.,  0.,  0.,  0.],
       [-1., -1.,  0.,  0.],
       [-1., -1., -1.,  0.]])

### [ Item B ]

#### Saída Esperada:

In [119]:
np.array([[ 1.,  0.,  0.,  0.,  0.],
          [ 0.,  2.,  0.,  0.,  0.],
          [ 0.,  0.,  3.,  0.,  0.],
          [ 0.,  0.,  0.,  4.,  0.],
          [ 0.,  0.,  0.,  0.,  5.]])

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  2.,  0.,  0.,  0.],
       [ 0.,  0.,  3.,  0.,  0.],
       [ 0.,  0.,  0.,  4.,  0.],
       [ 0.,  0.,  0.,  0.,  5.]])

#### Ferramentas:

In [120]:
np.eye?

In [121]:
""" Operador *"""
np.multiply?

#### Solução:

In [122]:
np.eye(5) * np.array([1, 2, 3, 4, 5])

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  2.,  0.,  0.,  0.],
       [ 0.,  0.,  3.,  0.,  0.],
       [ 0.,  0.,  0.,  4.,  0.],
       [ 0.,  0.,  0.,  0.,  5.]])

### [ Item C ]

#### Saída Esperada:

In [123]:
np.array([[ 0.,  1.,  2.,  3.,  4.],
          [-1.,  0.,  1.,  2.,  3.],
          [-2., -1.,  0.,  1.,  2.],
          [-3., -2., -1.,  0.,  1.],
          [-4., -3., -2., -1.,  0.]])

array([[ 0.,  1.,  2.,  3.,  4.],
       [-1.,  0.,  1.,  2.,  3.],
       [-2., -1.,  0.,  1.,  2.],
       [-3., -2., -1.,  0.,  1.],
       [-4., -3., -2., -1.,  0.]])

#### Ferramentas:

In [124]:
np.ones?

In [125]:
""" Operador * """
np.multiply?

In [126]:
""" Operador + """
np.add?

#### Solução:

In [127]:
A = np.ones((5, 1))
B = np.array([[1, 2, 3, 4, 5]])
C = np.array([[1],
              [2],
              [3],
              [4],
              [5]])
A.dot(B) - C

array([[ 0.,  1.,  2.,  3.,  4.],
       [-1.,  0.,  1.,  2.,  3.],
       [-2., -1.,  0.,  1.,  2.],
       [-3., -2., -1.,  0.,  1.],
       [-4., -3., -2., -1.,  0.]])

### [ Item D ]

#### Saída Esperada:

In [128]:
np.array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
          [ 2,  4,  6,  8, 10, 12, 14, 16, 18],
          [ 3,  6,  9, 12, 15, 18, 21, 24, 27],
          [ 4,  8, 12, 16, 20, 24, 28, 32, 36],
          [ 5, 10, 15, 20, 25, 30, 35, 40, 45],
          [ 6, 12, 18, 24, 30, 36, 42, 48, 54],
          [ 7, 14, 21, 28, 35, 42, 49, 56, 63],
          [ 8, 16, 24, 32, 40, 48, 56, 64, 72],
          [ 9, 18, 27, 36, 45, 54, 63, 72, 81]])

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 9, 18, 27, 36, 45, 54, 63, 72, 81]])

#### Ferramentas:

In [129]:
A = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [130]:
np.dot?

In [131]:
np.transpose?

#### Solução:

In [132]:
A.T.dot(A)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 9, 18, 27, 36, 45, 54, 63, 72, 81]])

### [ Item E ]

#### Saída Esperada:

In [133]:
np.array([[-18,   0,  18]])

array([[-18,   0,  18]])

#### Ferramentas:

In [134]:
A = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
B = np.array([[-1, 0, 1]])
C = np.array([[0, 0, 1, 0, 0, 1, 0, 0, 1]])

In [135]:
np.dot?

In [136]:
np.transpose?

#### Solução:

In [137]:
C.dot(A.T.dot(B))

array([[-18,   0,  18]])